// GENERATED by build-app.js from ni-booking-page.html - do not edit by hand.
// Working hours, meeting types and closures. Change them in the source page.

export const CAIRO = "Africa/Cairo";

export const DAY_START = 9 * 60 + 30;   // 09:30 Cairo
export const DAY_END   = 16 * 60 + 30;  // 16:30 Cairo
export const BREAK_A   = 13 * 60;       // midday hold starts
export const BREAK_B   = 14 * 60;       // midday hold ends
export const STEP      = 30;            // slot granularity, minutes
export const HORIZON_WEEKS = 3;

export const HOLIDAYS = { "2026-08-25": { en: "Mawlid — public holiday", ar: "المولد النبوي — إجازة رسمية" } };

export const TYPES = [
    { id: "call",    mins: 20, notice: 1, en: "Quick call",          ar: "مكالمة سريعة" },
    { id: "commercial", mins: 45, notice: 1, en: "Commercial / RFQ",  ar: "تجاري / طلب عرض سعر" },
    { id: "technical",  mins: 45, notice: 1, en: "Technical review",  ar: "مراجعة فنية" },
    { id: "internal",   mins: 30, notice: 1, en: "Team one-to-one",   ar: "اجتماع فردي للفريق" },
    { id: "visit",      mins: 90, notice: 3, en: "Factory visit",     ar: "زيارة المصنع" }
  ];
